<?php
namespace rhinoplusfacile\entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-07-24 at 11:01:20.
 */
class AccessibleEntityTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AccessibleEntity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AccessibleEntity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
